### PR TITLE
Unswf - decompress swf files

### PR DESCRIPTION
**Pull request by frbapolkosnik**
This is useful to expose some hardcoded strings in compressed flash files. Currently it should support both zlib, and lzma compressed files. pyliblzma required.

### CODE REVIEW

**Comment by wxsBSD** [comment]
This is a good addition. I grabbed a bunch of flash files from VT and it seemed to work well on most of them, but had some problems with others. I know nothing about the flash file format but the obvious thing in common with the ones that work is they start with CWS and the ones that do not are all ZWS. Here are three hashes of ones that don't decompress properly:

270533e84d9dc5b978699892d37313d3
b306fbd2a87a7f44f8764c1664fe491c
c7dce4408ce25a91971bf2c76a30c7b3

If you need copies of these just let me know. I'd like to fix that up before accept this as it does claim to work with those.

**Comment by frbapolkosnik** [comment]
I'm working an a fix.

**Comment by frbapolkosnik** [comment]
Switched to pylzma (https://pypi.python.org/pypi/pylzma) and it works as intended, update to follow.

**Comment by frbapolkosnik** [comment]
Fixed

**Comment by wootski** [comment]
Adding flash decompression would be great :). Any plans to do additional work in this area <b>frbapolkosnik</b>? I have only had time for a brief look at possible work in this area (https://github.com/wootski/crits_services/tree/swfinfo/swfinfo_service) as it is not one of the key items I had planned to work on.

**Comment by wxsBSD** [comment]
Thanks. I'm going to be AFK all day tomorrow but should have some time at night this weekend to check out the update and merge this in.

**Comment by apolkosnik** [comment]
This was made to scratch a certain itch, but it can be expanded further.
Thanks for the pointers.

Adding flash decompression would be great :). Any plans to do additional
work in this area *frbapolkosnik*? I have only had time for a brief look at
possible work in this area (
https://github.com/wootski/crits_services/tree/swfinfo/swfinfo_service) as
it is not one of the key items I had planned to work on.

—
Reply to this email directly or view it on GitHub
<https://github.com/crits/crits_services/pull/97#issuecomment-83796928>.

**Comment by apolkosnik** [comment]
I already have exiftools service to tell me the details of the most files,
but I guess I can try to quickly add stuff similar to swf.py from
jsunpack-n.

**Comment by wxsBSD** [comment]
Thanks for this Adam! :)

**Pull request merged**
