### PR TITLE
updated pdfparser.py

### PR DESCRIPTION
**Pull request by boddumanohar**
* solves null value output
* Detailed description of what the indirect objects.

### CODE REVIEW

**Comment by boddumanohar** [comment]
Credits: https://blog.didierstevens.com/2015/04/16/pdf-parser-a-method-to-manipulate-pdfs-part-1/

**Comment by mgoffin** [comment]
I need to get on testing this. My apologies.

**Comment by boddumanohar** [comment]
Is this still being tested? Please let me know if there is anything that I have to change.

Thanks.

**Comment by boddumanohar** [comment]
What is the status of this pull?

**Comment by boddumanohar** [comment]
Is this still being tested? Please let me know if there is anything that I have to change.

Thanks.

**Pull request closed without merging**
