### PR TITLE
malshare service (issue #110)

### PR DESCRIPTION
**Pull request by theevilbit**
Hi,

I created a service, which allows downloading a sample from MalShare (http://malshare.com), if there is no filedata to the actual sample in the database. The service uses MalShare's public API, and an API key is required.

If the sample is not found, it will indicate it, and if there is already a sample in the DB, it will not try to download it.

Screenshots:

screen shot 2015-09-21 at 22 04 37
screen shot 2015-09-21 at 22 05 05
screen shot 2015-09-21 at 22 05 39

### CODE REVIEW

**Comment by ssanthosh243** [comment]
I encountered an error when using exiftool service. When i execute the service it is giving me the below error:

Error running service: No JSON object could be decoded

Please help me out.

Thanks,
Sai Santosh

**Comment by theevilbit** [comment]
Try to run exiftool manually in terminal, this way: "exiftool -json filename"
Check if it produces json output, if not, you need to update your exiftool version.

**Comment by ssanthosh243** [comment]
Yes I am able to run the command and get the result, But i'm not able to get the result with the service.

**Comment by ssanthosh243** [comment]
I have encountered the below error in the logs:

[Fri Sep 25 16:16:43.252921 2015] [:error] [pid 2469:tid 140213894506240] 65884 ERROR: Error running service exiftool
[Fri Sep 25 16:16:43.253050 2015] [:error] [pid 2469:tid 140213894506240] Traceback (most recent call last):
[Fri Sep 25 16:16:43.253062 2015] [:error] [pid 2469:tid 140213894506240]   File "/data/crits/crits/services/core.py", line 438, in execute
[Fri Sep 25 16:16:43.253072 2015] [:error] [pid 2469:tid 140213894506240]     self.run(self.current_task.obj, config)
[Fri Sep 25 16:16:43.253082 2015] [:error] [pid 2469:tid 140213894506240]   File "/data/services/exiftool_service/__init__.py", line 85, in run
[Fri Sep 25 16:16:43.253093 2015] [:error] [pid 2469:tid 140213894506240]     results = json.loads(output.decode('utf-8'))[0]
[Fri Sep 25 16:16:43.253102 2015] [:error] [pid 2469:tid 140213894506240]   File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
[Fri Sep 25 16:16:43.253112 2015] [:error] [pid 2469:tid 140213894506240]     return _default_decoder.decode(s)
[Fri Sep 25 16:16:43.253122 2015] [:error] [pid 2469:tid 140213894506240]   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
[Fri Sep 25 16:16:43.253132 2015] [:error] [pid 2469:tid 140213894506240]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[Fri Sep 25 16:16:43.253142 2015] [:error] [pid 2469:tid 140213894506240]   File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
[Fri Sep 25 16:16:43.253152 2015] [:error] [pid 2469:tid 140213894506240]     raise ValueError("No JSON object could be decoded")
[Fri Sep 25 16:16:43.253162 2015] [:error] [pid 2469:tid 140213894506240] ValueError: No JSON object could be decoded

**Comment by theevilbit** [comment]
Please continue conversation here: https://github.com/crits/crits_services/pull/154

**Pull request merged**
