### PR TITLE
Add more options to cuckoo_service.

### PR DESCRIPTION
**Pull request by eltair**
Global config options added:
  * https for API calls
  * timeout value
  * enforce_timeout

Runtime config options added:
  * enforce_timeout

### CODE REVIEW

**Comment by mgoffin** [comment]
These changes seem pretty sane. Anyone using cuckoo that can test these out, or at least make sure it doesn't break any existing setups?

**Comment by wxsBSD** [comment]
Paging @echin20. He can probably test these out.

**Comment by gtback** [comment]
@robertsjw might also be able to test this out.

**Comment by wxsBSD** [comment]
This looks fine, we'll test it out in production soon.

**Pull request merged**
