### PR TITLE
Bootstrap upgrade

### PR DESCRIPTION
**Pull request by frbapolkosnik**
Revamped the bootstrap for services to resemble the one in crits repo
- the script traverses subfolders and executes "bootstrap" files
each bootstrap does some OS specific installs and also pip install -r is run against "requirements.txt" files in that service folder.

Dependencies that should work "out of the box" after bootstrap is executed:
+ OPSWAT_Service
+ anb_service
+ c1fapp_service  - requests
+ carver_service
+ chminfo_service
+ clamd_service - needs manual config
+ cuckoo_service
+ data_miner_service
+ diffie_service
+ entropycalc_service
+ exiftool_service
+ farsight_service
+ machoinfo_service
+ malshare_service
+ meta_checker
+ office_meta_service
+ opendns_service
+ passivetotal_service
+ pdf2txt_service
+ pdfinfo_service
+ peinfo_service
+ preview_service
+ pyinstaller_service
+ relationships_service
+ shodan_service
+ ssdeep_service
+ stix_validator_service
+ threatgrid_service
+ threatrecon_service
+ timeline_service
+ totalhash_service
+ unswf_service
+ upx_service
+ virustotal_service
+ whois_service
+ yara_service
+ zip_meta_service

Dependencies for the following services need some manual setup (at least until somebody fixes them):
- chopshop_service
- metacap_service —needs chopshop
- pyew
- snugglefish_service
- taxii_service

### CODE REVIEW

**Comment by mgoffin** [comment]
Hmm. I don't see this traversing and using bootstrap files for all of the different services. I see a single bootstrap script that does all of the services whether you want them or not.

To be clear, I see the traversing function, but I don't see any of the requirements.txt or bootstrap scripts for the individual services.

**Comment by frbapolkosnik** [comment]
Look in the  for loop at 78 and 89.

**Comment by mgoffin** [comment]
And as I clarified in my previous statement, there are no bootstrap or requirement files for any of the other services included in this PR. Your single bootstrap script just installs everything on its own. I am saying that it should literally install nothing, and just call the bootstraps and requirements for each of the individual services.

**Comment by frbapolkosnik** [comment]
I'll add bootstrap files and requirements.txt files to each of the service folders in the next commit, if that's what you meant.

**Comment by mgoffin** [comment]
What I mean is that this entire thing shouldn't be like this. The "all encompassing" bootstrap shouldn't do a single thing involved in installing anything. It should be very dumb. The only thing it should do is execute the bootstrap for each service that has one. Then each individual service bootstrap would call the appropriate requirements.txt file if necessary and handle the entire installation process for that service.

**Comment by frbapolkosnik** [comment]
I'm reworking it now, it'll export the OS, REL, and REV. I'm removing the OS dependent parts once I get that stuff copied to the appropriate services

**Comment by frbapolkosnik** [comment]
It looks like deps for chopshop and taxii will need some more work.

**Comment by gtback** [comment]
This really increases the amount of code/effort needed to write new services, which seems a bit unfortunate to me :frowning: 

I'm glad there is some automated way to install service dependencies, but a 150-line shell script for each service seems excessive. I would prefer to see a small "requirements-style" file for each service, which lists (for example) Ubuntu dependencies, RHEL dependencies, Python dependencies, Brew dependencies, etc. Then all the logic to read these files and install the dependencies could be in the single bootstrap script. The current approach seems like it could become a maintenance nightmare.

**Comment by frbapolkosnik** [comment]
It's a start, you are welcome to rework this into something that is less of a maintenance nightmare. There is some fluff there, but it was meant as a starting point, and the examples are there; besides it works when it's started from service folder, as well as the crits_services.

**Comment by frbapolkosnik** [comment]
There are already a few things offloaded to funcs.sh,

**Comment by mgoffin** [comment]
It may not be the best, but it's a great start, and i don't anticipate having to copy/paste a file and changing a couple lines is going to cause much of a headache in the meantime. Most people do that anyways with a service they are already comfortable with as a template.

**Pull request merged**
