### PR TITLE
Malicious Macro Bot Service

### PR DESCRIPTION
**Pull request by echin20**
This service is utilizing Evan Gaustad Malicious Macro Bot Project.

https://github.com/egaus/MaliciousMacroBot

### CODE REVIEW

**Comment by mrichard91** [comment]
If you install this using PIP and the requirements.txt the model files end up in the site packages. This isn't that intuitive and there are no instructions telling you how to do this. Can you add some documentation or other hints on how to find the model directory? 

In my case after PIP installing it ends up int he dist-packages dir.

/usr/local/lib/python2.7/dist-packages/mmbot/model/

**Comment by mrichard91** [comment]
One other comment on the presentation of the results - I think it would make sense to break the results into two groupings - one for the actual prediction and another for the features. This would make it a lot easier to pick out what the model thinks as compared with the features.

**Comment by echin20** [comment]
Thanks @mrichard91 for the feedback on the service. The result suggestion make sense and I modified the output to reflect your suggestion. As far as the model directory. I made the service so that it is required in the form field to specify where that path exist. That should override the default path. 

Also thanks to @mgoffin for point out that I can pass the data file in as a variable instead of writing it to the disk.

**Comment by mrichard91** [comment]
I've been running this as a triage service and noticed that it runs against all files, and tags non-office documents as malicious. Can we also limit this to only run against Office documents?

**Comment by mgoffin** [comment]
Seems like a good idea. Do we have an accurate/up-to-date/working class method for samples for office documents similar to "is_pe()" and "is_pdf"? Would be useful and make it easy to call within the service instead of writing it here and no other potential services getting to leverage it.

**Comment by mrichard91** [comment]
Another comment on how the results are added - the result field is actually the field name, which doesn't allow you to pivot on results.  Every analyzed sample will end up with the same field names in the result field.

Currently you are doing this:
  self._add_result("Features", k, {"value": v})
But I think you should do:
  self._add_result("Features", v, {"value": v, "name": k}

**Comment by echin20** [comment]
@mrichard91, I agree the pivot didn't make sense to me on my first past. However, didn't know how well the number values would be either. So I am glad for you are giving the feedback. I made the changes as you suggested for the pivoting. 

Also I did notice when I submit a exe file it mark it as malicious too. With that said I didn't realize there was an option in CRITs to limit file type with the service. I took a stab at putting in @mgoffin suggestion on the CRITs side. Hopefully I did it correctly in CRITs as I normally develop on CRITs service side.

**Comment by mgoffin** [comment]
You added the method properly. Assuming the actual check is accurate it should be fine :)

**Pull request merged**
