### PR TITLE
[NEW] Threatgrid service

### PR DESCRIPTION
**Pull request by wootski**
This service can be configured to interact with a ThreatGRID applicance for the purpose of submitting files for dynamic analysis. The service will collect a subset of the analysis results and display them in CRITS.

Key features:
* Submit files for dynamic analysis
* Retrieve and display ThreatGRID analysis results
* Add new indicators to CRITS based on the information returned from ThreatGRID

Comments:
* As you may not have an appliance to test with, I can provide screenshots of the CRITS service output if necessary.

Future work:
* Retrieve any additional indicators from ThreatGRID (process created, files dropped etc.)
* Support additional types: IP, domain lookups etc.

### CODE REVIEW

**Comment by mgoffin** [comment]
Awesome!

**Comment by mgoffin** [comment]
I don't have access to ThreatGRID appliances, so if you do have those screenshots available I'd be interested to review them to make sure the rendering looks sane.

The code looks good to me even though I can't test it. But I suspect since this has no dependencies outside of what CRITs already requires (from what it looks like, I don't see a DEPENDENCIES file here. Might want to add it?) it wouldn't hurt to include it and get feedback from people who try it and have issues.

**Comment by wootski** [comment]
I have updated the dependencies file and have included the screenshots in this comment. 

I could improve the "submitted_at" time displayed by the plugin (by converting it to the CRITS server's localtime) but I was hesitant to require an additional python package (pip install pytz) just for that; happy to add it in if requested.

tg_results_1
tg_results_2

**Comment by mgoffin** [comment]
That looks great! So this is just a summary of the returned data and if users want they can use the "Add/Edit" to add Indicators, similar to how the Data Miner works?

**Comment by wootski** [comment]
Yeah it includes the more interesting data provided by ThreatGRID and creates a unique list of the network indicators at the bottom, allowing users to add them; it works in exactly the same manner as DataMiner.

The results show "threatgrid_submitted" for samples that have not been previously analyzed and all the additional results are added when the analysis has been completed.

**Comment by mgoffin** [comment]
I'm going to merge this in. It looks great and will hopefully see some use by other folks who work with ThreatGRID. I'm sure it'll go through the paces and adjustments can always be made in the future. Thanks for doing this!

**Comment by wxsBSD** [comment]
Well, I'm glad @mgoffin beat me to this. It was on my TODO list for today! This looks like a nice service, thank you for the work! :)

**Pull request merged**
