### PR TITLE
TAXII Service Updates

### PR DESCRIPTION
**Pull request by brlogan**
This PR contains a significant number of changes to the CRITs TAXII Service, adding new functionality, and also repairing functionality that was lost when STIX/TAXII was pulled from the core CRITs code.  It has not gone through extensive testing, but it seems stable for me so far, so I'd like to get it out there.

The TAXII service now supports:
- Configuration of multiple TAXII servers
- Configuration of multiple feeds per server
- Basic or certificate authentication, or both
- Consumption of both encrypted and unencrypted TAXII content blocks
- Polling by individual feed, or multiple feeds at once
- Preview of STIX data prior to import into CRITs
- Selective import of STIX data by content block

This PR does not address the need for additional parsers to translate between STIX types and the new CRITs vocabulary.

### CODE REVIEW

**Comment by mgoffin** [comment]
Yay! I am not sure what the conflicts are, but if you could do a quick merge with master and make sure it looks good we can accept this :)

**Comment by brlogan** [comment]
Dang it! I thought I took care of that. I'll have it fixed in a jiffy!

**Comment by brlogan** [comment]
Okay, I think that should do it.

**Comment by mgoffin** [comment]
Thank you!! :)

**Comment by brlogan** [comment]
You're welcome! I'm looking forward to feedback. There is plenty more that needs to be done to make this thing solid, but I think people will be happy with the updates.

**Comment by treyka** [comment]
@brlogan Nice work, mate! ^_^

**Comment by mgoffin** [comment]
I'm not sure if I'm seeing something weird, but the "TAXII Service" tab for sending content from CRITs  has no configuration options showing. Is that because I have no TAXII servers configured?

**Comment by apolkosnik** [comment]
@brlogan, Thanks for getting this done. Awesome stuff!

**Comment by brlogan** [comment]
@mgoffin: Yes, that would do it. The "TAXII Service" tab's "Recipient" box will be empty if you don't have any servers/feeds configured. The "TAXII Agent" page's "TAXII Feeds" will also be empty in that case. Did you try configuring some servers/feeds?

**Comment by mgoffin** [comment]
I did not. I don't ever plan on using it ;) Was just making sure that was intended.

**Comment by frbapolkosnik** [comment]
Occurances of 'mimetype=' need to be changed to 'conetnt_type=' in view.py

**Comment by brlogan** [comment]
You caught me. Hadn't updated Django yet. Thanks!
Fix: https://github.com/crits/crits_services/pull/200

**Comment by brlogan** [comment]
@mgoffin: Do I understand correctly that you were seeing an empty Recipients MultipleChoiceField?  If so, I suppose I could hide the fields add a message directing the user to configure their TAXII Service, rather than just showing blank fields. Is that more inline with what you were expecting?

**Comment by mgoffin** [comment]
I didn't see that either. Just a "preview" and "submit" button (I think it's submit or something). No form to fill out or any indication that a form might exist.

**Comment by brlogan** [comment]
@mgoffin: Ah, okay. I'm pretty sure that problem was addressed by #200. When you get a chance to pull that into your instance, please let me know if the form still does not load.

**Comment by apolkosnik** [comment]
I'm getting 'NoneType' has no attribute 'strftime', when trying to connect to a brand new feed, and 'Get all messages since last full poll' is checked.

**Comment by brlogan** [comment]
@apolkosnik: Well that's a silly bug. Good catch. Fixed with #201.

**Comment by frbapolkosnik** [comment]
Sorry for the brevity there, I was trying to convey that over a cell phone :-) It all seems to be a OK with the commercial taxii server, the only issue for pulling down indicators is that the non-Cybox compliant ones end up as empties. I'll test submissions later on today.

Thanks again for getting this awesome piece of code out!

**Comment by frbapolkosnik** [comment]
I was trying to set up the feeds from hailataxii, but I'm getting timeouts, Has anyone run into that?

Would it make more sense to use the discovery service URI for setting up the new feeds instead of hostname, port, poll, and inbox settings?

**Comment by brlogan** [comment]
@frbapolkosnik: Feed discovery is one of the features that is not yet implemented, so you can't do that right now.  Are you getting timeouts while trying to configure the feeds, or when trying to poll after configuration?

**Comment by apolkosnik** [comment]
Timeout happens when I try to poll.

**Comment by brlogan** [comment]
@apolkosnik: Hmm, first let's make sure your configuration is correct. Try this:
screen shot 2016-03-03 at 12 51 44 pm

**Comment by frbapolkosnik** [comment]
I had poll and inbox paths wrong, thanks!

**Comment by jezkerwin** [comment]
I love the new service, thanks for this. Quick question. Does the service support the server sitting behind a proxy server?

**Comment by brlogan** [comment]
@jezkerwin: Yes, it does. The service uses the general CRITs proxy settings.

**Comment by frbapolkosnik** [comment]
Ugh, I'm not seeing any hits in my proxy, so it seems that it's not applying the proxy for connections.

**Comment by frbapolkosnik** [comment]
PROXY_HTTPS gets set, but not PROXY_HTTP.

**Comment by jezkerwin** [comment]
does the setting support authentication for the proxy?

**Comment by jezkerwin** [comment]
@frbapolkosnik how are you checking which variables are being set?

**Comment by frbapolkosnik** [comment]
I was not seeing anything to hailataxii.com in my proxy logs. #203 fixes that,

**Comment by brlogan** [comment]
I believe I pretty much just used the existing code to handle the proxy connection and it's pretty basic. There is currently no support for proxy authentication and I'm not sure what support there is for that in libtaxii.  I'll take a look.

**Comment by frbapolkosnik** [comment]
https seems to be working for me with this change.

**Comment by brlogan** [comment]
@jezkerwin: It seems that libtaxii currently has no support for authentication to a proxy, but neither does CRITs.

**Comment by jezkerwin** [comment]
@brlogan thanks for that. I'll look into whitelisting the CRITs server to not require authentication.

**Comment by monkeydox** [comment]
Is there any future plans to be able to set polling period for feeds ?

**Comment by brlogan** [comment]
@monkeydox: Can you provide some more detail about what you're looking for? Do you mean scheduling automatic polling of feeds?

**Comment by monkeydox** [comment]
Yes, looking to set up schedules for the configured feeds.

**Pull request merged**
