### PR TITLE
added kevthehermit ratdecoder as crtis service

### PR DESCRIPTION
**Pull request by nosferatu87**
I rewrote https://github.com/kevthehermit/RATDecoders into a crits service to easily get rat config information.

### CODE REVIEW

**Comment by frbapolkosnik** [comment]
Very nice!

**Comment by mgoffin** [comment]
Awesome utility! Saddens me that it is GNU licensed as that's going to severely limit people being able to use it (most people will wish to add their own non-sharable parsers and yara rules which would require them to make them available).

Also, the following lines...are they there for kicks? Are they legit necessary? Can they be removed?
* https://github.com/crits/crits_services/pull/229/files#diff-35507195e2feccf4a32d53e55c94b076R173
* https://github.com/crits/crits_services/pull/229/files#diff-35507195e2feccf4a32d53e55c94b076R174

**Comment by nosferatu87** [comment]
To be honest, those lines are unaltered from Kevin's repo so I would assume they are required. I can't verify that for you though as I can't prove those keys aren't used in some AlienSpy versions.

**Comment by kevthehermit** [comment]
Awsome use of the repo. :) 
Yes those lines are required if you want several versions of the alienspy decoders to work. The malware Author took issue with me reverse engineering his code this was his way of telling me so.

**Comment by mgoffin** [comment]
@kevthehermit that's sort of amazing, haha. And just to confirm, this has to be GNU licensed?

**Comment by kevthehermit** [comment]
Someone needs to talk to me about what license will work best here. Its most important to me that the code stays open and that the community gets the support and benefit from this. 

The idea of creating a modular framework is that the core could be maintained independent of adding your own plugins. If you drop your own plugin your not modifying the framework and therefore dont need to redistribute with your own plugins you have added.

**Comment by mgoffin** [comment]
There was a rather large, lengthy discussion when open sourcing CRITs as to whether or not services would need to also be GNU licensed if the core was GNU licensed. Lawyers and others included, it was very muddy whether or not that was the case due to how the code got imported.

We decided to go MIT to ensure it wasn't an issue and no one needed to worry about it. It was more important to us to make a license that was easy to see, understand, use, and not worry about than to deal with something that would require lawyers to get involved to see if your organization could use/contribute to.

**Comment by kevthehermit** [comment]
Okay makes sense thanks, Will switch mine to MIT.

Also just to clarify i was referring to my own framework in my previous post. Didn't want to sound like i was making comments about the CRITS licensing type :)

**Comment by mgoffin** [comment]
Yea I got you. Figured our example might inform you at least of how we handled a similar situation.

**Comment by webstergd** [comment]
Just to chime in. I have found that MIT, BSD, and Apache2 are by far the
best when dealing with corporations. ... We recently went though an
exercise with a number of lawyers to identify the best license for some of
our opensource projects.

**Comment by mgoffin** [comment]
@webstergd agreed! We settled on MIT just due to the overwhelming amount of JavaScript libraries and web frameworks that also used it that we were looking at and using in the project.

**Comment by mgoffin** [comment]
Excellent. I'll accept and if any edge cases come up they can be worked out after :) Thanks for writing this!

**Pull request merged**
