### PR TITLE
Add exiftool service

### PR DESCRIPTION
**Pull request by theevilbit**
Created the exiftool service, which will run Phil Harvey's exiftool on a binary, and store its output. Screenshot:

screen shot 2015-09-20 at 08 48 29

### CODE REVIEW

**Comment by theevilbit** [comment]
What is your environment? Linux version, python version? I use latest Ubuntu LTS and latest Python.

**Comment by ssanthosh243** [comment]
I am using Python 2.7.6 on Ubuntu 14.04.

**Comment by theevilbit** [comment]
Weird. The same environment here. Do you have the correct path set? For me its: "/usr/bin/exiftool"

**Comment by theevilbit** [comment]
Can you add this to line 83 in __init__.py?

            logger.debug(output)
            self._debug(output)

It will log exiftool's raw output to the logs. Can you paste the debug output here?

**Comment by ssanthosh243** [comment]
Hi,

I got the following error in the Crits log file.

    self.run(self.current_task.obj, config)
  File "/data/services/exiftool_service/__init__.py", line 85, in run
    # exiftool will return its results in json, and it will be inside a single element list
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ssanthosh243** [comment]
root@vps40544:/data/logs# tail -f crits.log
    self.run(self.current_task.obj, config)
  File "/data/services/exiftool_service/__init__.py", line 85, in run
    # exiftool will return its results in json, and it will be inside a single element list
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by theevilbit** [comment]
Is that the same on the GUI log output? Something doesn't look right in your setup. This log should contain exiftool's output, whatever it is. Can you reinstall the service from scratch?

**Pull request merged**
