### PR TITLE
Replace StringIO with BytesIO - verification pending

### PR DESCRIPTION
**Pull request by frbapolkosnik**
Replace StringIO with BytesIO for more portable code.

### CODE REVIEW

**Comment by frbapolkosnik** [comment]
- daily_samples.py verified working with io.BtesIO()
- get_file_yara.py fixed to work with 4.0 and verified working properly with io.BytesIO()
- pdfinfo_service changes verified working properly with io.BytesIO()

**Comment by frbapolkosnik** [comment]
# 4 simple tests for BytesIO and StringIO...
import io
xml = u'test'
xml2 = 'test2'
xml2 = xml2.encode('utf-8').strip()
# test with unicode
f = io.StringIO(xml)
print f
# test with a string
g = io.BytesIO(xml2)
print g
# test with unicode
try:
    g = io.BytesIO(xml)
    print g
except Exception as e:
    print e
# test with a string
try:
    f = io.StringIO(xml2)
    print f
except Exception as e:
    print e

$ python main.py                                                                                                           
<_io.StringIO object at 0x7f8d041085d0>                                                                                          
<_io.BytesIO object at 0x7f8d04170bf0>                                                                                           
'unicode' does not have the buffer interface                                                                                     
initial_value must be unicode or None, not str 

So, it looks like we can use io.BytesIO unless we deal with unicode.

**Comment by mgoffin** [comment]
We have to deal with Unicode fairly often. If we have to go through hoops to do conversions just to use BytesIO it might not be worth it.

**Comment by dsnellgrove** [comment]
Just use StringIO for your text (unicode) and BytesIO for your data (bytes). Since Django and MongoDB support unicode end-to-end for their text you would not have to convert hardly ever. The only exception would be if you want to extract text from a submitted file such as a CSV or email upload.

**Comment by frbapolkosnik** [comment]
It's fine, StringIO.StringIO() converts to io.BytesIO() without any extra tweaking.

**Pull request merged**
