### PR TITLE
PassiveTotal Service v2

### PR DESCRIPTION
**Pull request by passivetotal**
This is a complete rewrite of the PassiveTotal service to support the new version of our API (https://api.passivetotal.org/api/docs/). This version will support the following queries:

- Passive DNS
- WHOIS
- WHOIS search by Email
- SSL certificates
- SSL certificate history
- Subdomains
- Enrichment
- Trackers
- Components
- OSINT
- Malware

Additionally, we have updated our forms to support letting users select each one of these services or not getting any prompts at all. Each particular query takes in a number of different types to allow for the most complete flexibility.

### CODE REVIEW

**Comment by passivetotal** [comment]
Bumping @mgoffin since this doesn't touch the trunk at all and should be a simple pull to accept!

**Comment by mgoffin** [comment]
Looks good :) I'll accept and fix up one little thing (in DEPENDENCIES just need to change it from requests to the passivetotal library).

Thanks for putting this together!! :+1:

**Comment by passivetotal** [comment]
Doh! Somewhere along the way, I must have clobbered that.

**Comment by mgoffin** [comment]
All good!

**Pull request merged**
