### PR TITLE
Quick fix to timeline breaking on a pcap

### PR DESCRIPTION
**Pull request by frbapolkosnik**

### CODE REVIEW

**Comment by mgoffin** [comment]
This doesn't fix what I think you expect it to fix. The name is required and if not set will use the last time the name variable was set which can cause dupes, potentially from the campaigns loop above this one.

With the start of the new vocabulary, Objects no longer have both a name and a type, so this entire block needs to be rewritten to accommodate that. Once that's done, it should fix the problem you are having.

**Comment by frbapolkosnik** [comment]
How's now?

**Comment by frbapolkosnik** [comment]
Splendid! The search results show Actors... I think I just saw Regan! ;-)

**Comment by mgoffin** [comment]
https://github.com/crits/crits/blob/master/crits/core/crits_mongoengine.py#L1031

Objects no longer have a name attribute. The whole concept of looking for a name should just go away :)

**Comment by frbapolkosnik** [comment]
ok, just removed the whole .name related piece for objects. Thanks for the hint.

**Pull request merged**
