### PR TITLE
Added better error handling to the PassiveTotal service

### PR DESCRIPTION
**Pull request by passivetotal**
Updates to the service:
- Added better error handling for when users fail authentication or hit query limits
- Updated the README file
- Updated DEPENDENCIES to parody the master

### CODE REVIEW

**Comment by passivetotal** [comment]
@mgoffin Show that love please.

**Comment by mgoffin** [comment]
Got some merge conflicts. I think it's because you're also trying to edit the DEPENDENCIES to make the change that already exists?

**Comment by passivetotal** [comment]
Correct, can we just ignore it or accept either master or my pull?

**Comment by mgoffin** [comment]
I'll have to manually pull this down and fix the merge conflicts and then push it and close the PR. It'll take me a bit to get to that if that's what you'd like to do. Otherwise feel free to just remove that change from your PR and I think we should be good.

**Comment by passivetotal** [comment]
@mgoffin Good to go!

**Pull request merged**
