### PR TITLE
VirusTotal Download Service

### PR DESCRIPTION
**Pull request by brlogan**
This service checks the VirusTotal database to see if it contains a sample matching the given md5.
If VirusTotal has the sample, the sample is downloaded to CRITs.

### CODE REVIEW

**Comment by r3comp1le** [comment]
might be missing:

from crits.services.core import Service, ServiceConfigError

**Comment by brlogan** [comment]
Wow, good catch. Apparently my service config never had any errors!

**Comment by r3comp1le** [comment]
Service works on manual run, but not having success with triage showing results.

INFO 2016-06-02 22:16:09,103 crits.services.handlers Running VirusTotal_Download on 575111f3ad951d59e76d50ce, execute=process

No errors in log either.  Also notice that its prohibiting other services to run on triage.  When you do a manual run of the service, you get 2 download results.

**Comment by brlogan** [comment]
Odd, it certainly runs on triage in our prod environment and only produces one download result.
I'll try to take a closer look sometime tomorrow.

**Comment by brlogan** [comment]
Okay, I found the Triage issue. I made a change literally years ago in CRITs core code to allow Triage of Metadata Only Samples, but the PR was lost when CRITs was open sourced.  I've submitted a new PR crits/crits#755 to address this.

I have not been able to reproduce the issue where you get 2 download results. Even with a manual run, I'm still seeing only 1 result.

**Comment by r3comp1le** [comment]
fixing the triage issue also fixed the double results.  Thanks.  All is working as expected now

**Pull request merged**
