### PR TITLE
Fix missing proxy settings for HTTP

### PR DESCRIPTION
**Pull request by frbapolkosnik**

### CODE REVIEW

**Comment by brlogan** [comment]
Hold up. I don't think it's this simple. If you make this change, HTTPS connections won't route through the proxy.

**Comment by brlogan** [comment]
Hold up. I don't think it's quite that simple. I believe this might prevent HTTPS communication.

**Comment by mgoffin** [comment]
Does that overwrite a single proxy entry or does it allow for both HTTP and HTTPS? I suspect it toggles it which is probably bad?

**Comment by brlogan** [comment]
Exactly. I believe it switches it to HTTP.

**Comment by frbapolkosnik** [comment]
If you don't set it for HTTP, then HTTP will not go through the proxy, but HTTPS will. So, this is ok.

**Comment by brlogan** [comment]
I just tested it for both HTTP and HTTPS. The second call to client.setProxy overrides the first one. So this change will make HTTP requests work, but not HTTPS.

**Comment by frbapolkosnik** [comment]
ok, based on the checkbox, we can use one or the other.

**Comment by brlogan** [comment]
I have this, along with some other updates, in #204

**Pull request closed without merging**
